server:
  port: 1053
  udpThreadPool: 20
  tcpThreadPool: 4
  webPort: 8044
  httpThreadPool: 10

cache:
  enabled: true
  maxCacheEntries: 1000
  rewarm: true
  maxRewarmCount: 5

misc:
  timeout: 3
  dnssec: "simple"
  refreshLists: false
  serveExpired: false

resolver:
  tlsPoolSize: 5
  multiplier: 3 #how many upstreams we will reach on each active remote query
  upstreams:
    - host: "cloudflare-dns.com"
      port: 443
      protocol: "doh"
      path: "/dns-query"
    - host: "dns.google"
      port: 443
      protocol: "doh"
      path: "/dns-query"
    - host: "dns.quad9.net"
      port: 443
      protocol: "doh"
      path: "/dns-query"
    - host: "dns.adguard.com"
      port: 443
      protocol: "doh"
      path: "/dns-query"
  localMappings:
    - domain: "karpov"
      ip: "192.168.68.113"
    - domain: "cronicle.intranet"
      ip: "192.168.68.126"
  allowLists:

  blocklists:
    - "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"

