server:
  port: 1053
  udpThreadPool: 20
  tcpThreadPool: 4
  webPort: 8044
  httpThreadPool: 10

cache:
  enabled: true
  maxCacheEntries: 1000
  rewarm: true
  maxRewarmCount: 5

misc:
  timeout: 3
  dnssec: "off"
  refreshLists: false
  serveExpired: false

resolver:
  tlsPoolSize: 5
  multiplier: 2 #how many upstreams we will reach on each active remote query
  upstreams:
    - ip: "208.67.222.222" # NO DNSSEC!
      port: 53
      protocol: "udp"
    - ip: "208.67.220.220" # NO DNSSEC!
      port: 53
      protocol: "udp"
  localMappings:
    - domain: "karpov"
      ip: "192.168.68.113"
    - domain: "cronicle.intranet"
      ip: "192.168.68.126"
  allowLists:

  blocklists:
    - "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"

