server:
  port: 53
  udpThreadPool: 10
  tcpThreadPool: 3
  webPort: 8044
  httpThreadPool: 10

cache:
  enabled: true
  maxCacheEntries: 1000
  rewarm: true
  maxRewarmCount: 5

misc:
  timeout: 3
  refreshLists: true
  serveExpired: false
  dnssec: simple

resolver:
  tlsPoolSize: 5
  multiplier: 1 
  upstreams:
    - ip: "1.1.1.1"
      port: 853
      protocol: "dot"
      tlsAuthName: "cloudflare-dns.com"
    - ip: "1.0.0.1"
      port: 853
      protocol: "dot"
      tlsAuthName: "cloudflare-dns.com"
    - ip: "149.112.112.112"
      port: 853
      protocol: "dot"
      tlsAuthName: "dns.quad9.net"
    - ip: "9.9.9.9"
      port: 853
      protocol: "dot"
      tlsAuthName: "dns.quad9.net"

  localMappings:

lists:
  blockLists:
    block: "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"